---
- name: Clean up multi-resource-app-ocp
  import_tasks: cleanup.yml
  when: with_cleanup | default(false) | bool

- name: Deploy multi-resource-app-ocp
  import_tasks: deploy.yml
  when: with_deploy | default(false) | bool

- name: Validate multi-resource-app-ocp
  import_tasks: validate.yml
  when: with_validate | default(false) | bool
