---
- name: Ensure namespace exists
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ namespace }}"
    context: "{{ context | default(omit) }}"
    host: "{{ server if (token | default('') | string | length) > 0 else omit }}"
    api_key: "{{ token if (token | default('') | string | length) > 0 else omit }}"
    verify_ssl: "{{ verify_ssl }}"
  when: non_admin_user == false

- name: Create PVC
  k8s:
    state: present
    definition: "{{ lookup('template', 'pvc.yml.j2') | from_yaml }}"
    context: "{{ context | default(omit) }}"
    host: "{{ server if (token | default('') | string | length) > 0 else omit }}"
    api_key: "{{ token if (token | default('') | string | length) > 0 else omit }}"
    verify_ssl: "{{ verify_ssl }}"
