---
app_name: multi-resource-app

# Set this value to true if using a non cluster admin user
non_admin_user: false

with_cleanup: false
with_deploy: false
with_validate: false

replicas: 1
service_type: ClusterIP
